name: Release

on:
  push:
    tags:
      - v*.*
      - v*.*.*

jobs:

  create-github-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
            - TODO: Automatically find changes...
          draft: false
          prerelease: false

  publish-artifacts:
    name: Publish artifacts to packages
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set RELEASE_VERSION variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Publish package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # @doc https://github.com/eskatos/gradle-command-action
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
          build-root-directory: kotlin
          wrapper-directory: kotlin
          # configuration-cache-enabled: true
          dependencies-cache-enabled: true
